version: '3.8'

services:
  db:
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword           # Set your root password
      MYSQL_DATABASE: world                       # Database name
      MYSQL_USER: mydbuser                        # MySQL user
      MYSQL_PASSWORD: mydbpassword                # MySQL user password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db                            # MySQL host (db is the service name)
      - MYSQL_PORT=3306                          # MySQL port
      - MYSQL_USER=mydbuser                      # MySQL user (same as above)
      - MYSQL_PASSWORD=mydbpassword              # MySQL password (same as above)
      - MYSQL_DATABASE=world                     # Database name (same as above)
      - DJANGO_SECRET_KEY=your-django-secret-key  # Replace with a generated secret key
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost
      - EMAIL_USE_TLS=True
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_HOST_USER=your-email@gmail.com      # Your email address
      - EMAIL_HOST_PASSWORD=your-email-password  # Your email password or app password (if using Gmail)
      - EMAIL_PORT=587

volumes:
  mysql-data:
